# Site settings
title: Ahmadreza Hadi
general_email: ariuthadi@gmail.com
# academic_email: your_academic_email@univ

description: > # this means to ignore newlines until "baseurl:"
  Interesteed in AI & Deep Reinforcement Learning.

# baseurl: "/academic-portfolio" # the subpath of your site, e.g. /blog/

url: "https://ahmadrezahadi.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: AhmadrezaHadi
linkedin_username: ahmadreza-hadi
# facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
